site_name: MapYourGrid
site_url: 'https://MapYourGrid.org/'
site_description: We empower individuals, communities and nations around the world to map the electrical grid. 
repo_name: 'MapYourGrid'
repo_url: 'https://github.com/open-energy-transition/MapYourGrid'

nav:
  - THE INITIATIVE : index.md
  - IMPACT: impact.md
  - STARTER-KIT: starter-kit.md
  - MAP IT📍: map-it.md
  - TOOLS AND STRATEGIES: tools.md
  - OUR PROGRESS : progress.md
  - QUESTIONS? : questions.md
  #- BLOG:
  #    2025:
  #      - "Liberate the Grid": blog/firstrename.md

copyright:    <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">
      Creative Commons Attribution 4.0 International License   </a> -  <a href="https://MapYourGrid.org/privacy-policy/"> Read our Privacy Policy</a> 

theme:
  name: material
  custom_dir: docs/overrides
  favicon: images/logos/MapYourGrid-logo.png
  logo: images/logos/MapYourGrid-logo.png
  palette:
    # Light Mode
    - scheme: default
      primary: custom
      accent: indigo
      toggle: false 
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.highlight
    - search.suggest
    - navigation.top
    - navigation.sections
    - content.image.zoom
    

extra_css:
    - stylesheets/extra.css
    - stylesheets/landing.css
    - stylesheets/blog.css
    - https://cdn.jsdelivr.net/npm/featherlight@1.7.14/release/featherlight.min.css


extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/open-energy-transition/MapYourGrid
  - icon: fontawesome/brands/discord
    link: https://discord.gg/a5znpdFWfD
  image: images/MapYourGrid.ico
  social_preview: images/website/mapyourgrid-preview.jpg

extra_javascript:
  - js/umami.js



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.md_in_html
  - admonition
  - pymdownx.details
  - attr_list


plugins:
  - glightbox
  - search

  
